---
- name: Create the volume file system
  filesystem:
    fstype: ext4
    dev: "{{ data_volume_device }}"

- name: Create the volume mount point
  file:
    path: /mnt/data
    state: directory

- name: Mount the volume
  mount:
    name: /mnt/data
    src: "{{ data_volume_device }}"
    fstype: ext4
    state: mounted
    opts: discard,defaults
