---
- name: Add apt key for yarn
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    state: present

- name: Add apt key for Beats
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add apt repository for Elastic
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/6.x/apt stable main
    state: present
    filename: yarn
    update_cache: yes

- name: Update apt repository cache
  become: yes
  apt:
    update_cache: yes

- name: Install Datadog and Filebeat Dependencies
  become: yes
  apt: pkg={{ item }} state=present
  with_items:
    - apt-transport-https
    - filebeat

- name: Ensures /etc/pki/tls/certs for Logz.io certificate
  become: yes
  file: path=/etc/pki/tls/certs state=directory

- name: Install Filebeat Logz.io certificate
  become: yes
  get_url:
    url: https://raw.githubusercontent.com/logzio/public-certificates/master/COMODORSADomainValidationSecureServerCA.crt
    dest: /etc/pki/tls/certs/COMODORSADomainValidationSecureServerCA.crt

- name: Set up the Datadog deb repo
  become: yes
  shell: "echo 'deb https://apt.datadoghq.com/ stable 6' > /etc/apt/sources.list.d/datadog.list"

- name: Import Datadog key
  become: yes
  shell: "apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 382E94DE"

- name: Update apt repository cache (again for Datadog)
  become: yes
  apt:
    update_cache: yes

- name: Install Datadog Agent
  become: yes
  apt: pkg={{ item }} state=present
  with_items:
    - datadog-agent

- name: Setup Datadog Config
  become: yes
  shell: "sed 's/api_key:.*/api_key: {{ datadog_key }}/' /etc/datadog-agent/datadog.yaml.example > /etc/datadog-agent/datadog.yaml"

- name: Enable logging in Datadog Config
  become: yes
  lineinfile:
    path: /etc/datadog-agent/datadog.yaml
    regexp: 'logs_enabled'
    line: 'logs_enabled: true'

- name: Run Datadog Service
  systemd:
    name: datadog-agent.service
    state: restarted
