AllCops:
  RunRailsCops: true
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - db/schema.rb
    - bin/spring
    - bin/setup
    - bin/rails
    - bin/rake

Metrics/LineLength:
  Max: 120
  # To make it possible to copy or click on URIs in the code, we allow lines
  # contaning a URI to be longer than Max.
  AllowURI: true
  URISchemes:
    - http
    - https

Syle/Documentation:
  Enabled: false
