require:
  - rubocop-performance
  - rubocop-rails
AllCops:
  NewCops: enable
  Exclude:
    - db/schema.rb
    - bin/spring
    - bin/setup
    - bin/rails
    - bin/rake
    - vendor/**/* # Vendor gem dir in Travis CI
    - bin/yarn

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - config/**/*

Lint/MissingSuper:
  Exclude:
    - app/components/**/*

Layout/LineLength:
  Max: 220
  # To make it possible to copy or click on URIs in the code, we allow lines
  # contaning a URI to be longer than Max.
  AllowURI: true
  URISchemes:
    - http
    - https

Metrics/AbcSize:
  # The ABC size is a calculated magnitude, so this number can be an Integer or
  # a Float.
  Max: 20

Style/Documentation:
  Enabled: false

Rails:
   Enabled: true

Rails/BulkChangeTable:
  Enabled: false

Rails/SquishedSQLHeredocs:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/FormatStringToken:
  Enabled: false
