require:
  - rubocop-performance
  - rubocop-rails
AllCops:
  NewCops: enable
  Exclude:
    - db/schema.rb
    - bin/spring
    - bin/setup
    - bin/rails
    - bin/rake
    - vendor/**/* # Vendor gem dir in Travis CI
    - bin/yarn
    - lib/tasks/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - config/**/*

Metrics/ClassLength:
  CountAsOne: ['array', 'heredoc', 'hash']

Lint/MissingSuper:
  Exclude:
    - app/components/**/*

Layout/LineLength:
  Max: 220
  # To make it possible to copy or click on URIs in the code, we allow lines
  # contaning a URI to be longer than Max.
  AllowURI: true
  URISchemes:
    - http
    - https

Metrics/AbcSize:
  # The ABC size is a calculated magnitude, so this number can be an Integer or
  # a Float.
  Max: 25

Metrics/MethodLength:
  Max: 13
  Exclude:
    - db/migrate/*
    - app/lib/sql.rb

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Rails:
   Enabled: true

Rails/BulkChangeTable:
  Enabled: false

Rails/SquishedSQLHeredocs:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Rails/ReversibleMigration:
  Exclude:
    - db/migrate/20160912004942_add_organization_to_students.rb
    - db/migrate/20160916230442_add_subject_to_lesson.rb
    - db/migrate/20161008013423_add_mlid_to_students.rb
    - db/migrate/20161013042217_add_timestamps_to_grades.rb
    - db/migrate/20161016225911_change_deleted_at_to_datetime_in_grades.rb
    - db/migrate/20161016230051_change_deleted_at_to_datetime_in_subjects.rb
    - db/migrate/20161016234425_add_timestamps_to_grade_descriptors.rb
    - db/migrate/20161019013750_add_timestamps_to_assignments.rb
