AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - db/schema.rb
    - bin/spring
    - bin/setup
    - bin/rails
    - bin/rake
    - vendor/**/* # Vendor gem dir in Travis CI

Metrics/LineLength:
  Max: 120
  # To make it possible to copy or click on URIs in the code, we allow lines
  # contaning a URI to be longer than Max.
  AllowURI: true
  URISchemes:
    - http
    - https

Style/Documentation:
  Enabled: false

Rails:
   Enabled: true
