dist: trusty
language: ruby

services:
- postgresql

before_script:
- psql -c 'create database tracker_test;' -U postgres
    
script:
- RAILS_ENV=test bundle exec rake --trace db:migrate test

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2b5f267f968bbb52fee5
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

addons:
  postgresql: "9.5"
  code_climate:
      repo_token: 5db3f72ce9253ebdff56c2f98793691557a46415e09f70ab9c46036216d22580
