version: '3.7'
services:
  db:
    image: postgres:9.6.15
    restart: always
    environment:
      - POSTGRES_USER=tracker
      - POSTGRES_PASSWORD=tracker
    ports:
      - "5432:5432"

  web:
    environment:
      - DATABASE_HOST=db
    env_file:
      - .env
    build:
      context: .
      args:
        APP_ENV: dev # dev|prod
    image: tracker:dev
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
      - type: bind
        source: .
        target: /mindleaps/tracker
        volume:
          nocopy: true