version: '3.7'
services:
  db:
    image: postgres:9.6.15
    restart: always
    environment:
      - POSTGRES_USER=tracker
      - POSTGRES_PASSWORD=tracker
    ports:
      - "5432:5432"

  web:
    environment:
      - DATABASE_HOST=db
    env_file:
      - .env
    build: .
    image: tracker:dev
    command: bash -c "rake db:create && rake db:migrate && bundle exec bin/rails server -b 0.0.0.0"
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
      - type: bind
        source: .
        target: /mindleaps/tracker
        volume:
          nocopy: true