---
dependencies:
  - db_volume
  - role: geerlingguy.ansible-role-postgresql
    postgresql_data_dir: /mnt/data/db
    postgresql_databases:
    - name: tracker
    postgresql_users:
    - name: tracker
      password: "{{ database_password }}"
